// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    // ignore: missing_enum_constant_in_switch
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for ios - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
    }

    throw UnsupportedError(
      'DefaultFirebaseOptions are not supported for this platform.',
    );
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAR0pJVzKAkKQXjLy-hvjBTaegvxoNGSBI',
    appId: '1:51724019349:web:6e9e09cbff7c06c7e1dd9c',
    messagingSenderId: '51724019349',
    projectId: 'hot-or-cold-game-24c4c',
    authDomain: 'hot-or-cold-game-24c4c.firebaseapp.com',
    storageBucket: 'hot-or-cold-game-24c4c.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyA1d8Xk73t0lBBRXtmLtSet_-SubyLQCfs',
    appId: '1:51724019349:android:b370e124047c44e2e1dd9c',
    messagingSenderId: '51724019349',
    projectId: 'hot-or-cold-game-24c4c',
    storageBucket: 'hot-or-cold-game-24c4c.appspot.com',
  );
}
